// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp07s5VJZto_ZqQgZKFclfr3rVh-o25CA',
    appId: '1:96814630844:web:4a0ad209147ff0abfdcdb9',
    messagingSenderId: '96814630844',
    projectId: 'practicaflutterfirebase-6888b',
    authDomain: 'practicaflutterfirebase-6888b.firebaseapp.com',
    storageBucket: 'practicaflutterfirebase-6888b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy7QMpKTK5fjqQdhgtwgJrFwTY8ot7Hhk',
    appId: '1:96814630844:android:508ca939a6623facfdcdb9',
    messagingSenderId: '96814630844',
    projectId: 'practicaflutterfirebase-6888b',
    storageBucket: 'practicaflutterfirebase-6888b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxw-SAdq-dZ-s8G2F8RtlbeeSuJnxcfk',
    appId: '1:96814630844:ios:b454bfcbbd7855f8fdcdb9',
    messagingSenderId: '96814630844',
    projectId: 'practicaflutterfirebase-6888b',
    storageBucket: 'practicaflutterfirebase-6888b.appspot.com',
    iosClientId: '96814630844-g8eqsmus9v9mmvi84ek83gckvem9v5bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSupabaseLecturaSencilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzxw-SAdq-dZ-s8G2F8RtlbeeSuJnxcfk',
    appId: '1:96814630844:ios:b454bfcbbd7855f8fdcdb9',
    messagingSenderId: '96814630844',
    projectId: 'practicaflutterfirebase-6888b',
    storageBucket: 'practicaflutterfirebase-6888b.appspot.com',
    iosClientId: '96814630844-g8eqsmus9v9mmvi84ek83gckvem9v5bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSupabaseLecturaSencilla',
  );
}
